INSERT INTO "GROUP" VALUES (1, true);
INSERT INTO "GROUP" VALUES (2, false);

INSERT INTO CARD VALUES (1, true);
INSERT INTO CARD VALUES (2, false);
INSERT INTO CARD VALUES (3, true);
INSERT INTO CARD VALUES (4, false);
INSERT INTO CARD VALUES (5, true);
INSERT INTO CARD VALUES (6, false);

INSERT INTO GROUPACCESS VALUES (3, 1, 'DEFAULT');
INSERT INTO GROUPACCESS VALUES (4, 1, 'DEFAULT');
INSERT INTO GROUPACCESS VALUES (5, 2, 'GRANTED');
INSERT INTO GROUPACCESS VALUES (6, 2, 'FORBIDDEN');
